### ISSUE TITLE
Not working in Xojo 2021 Release 3.1

### ISSUE THREAD

**Issue by ValRaemaekers** [sworteu/Express#1]
Several issues when compiling with Xojo 2021 Release 3.1

**Comment by sworteu** [comment]
This should be working again.

**Comment by ValRaemaekers** [comment]
Hi
Thanks for attending to this so quickly :)
Still getting an error when running democaching,demotemplatesclientside,demotemplatesserverside
Also could you advise where to enable/disable the debug info below:
Dec 29 15:13:45  Express-Demo.debug[91535] <Warning>: Express.Server.AddSocket, socket: 12

**Comment by ValRaemaekers** [comment]
Thanks :)
Have added some comments some stuff still not working
Kind Regards
Val

**Comment by sworteu** [comment]
> Hi
> Thanks for attending to this so quickly :)
> Still getting an error when running democaching,demotemplatesclientside,demotemplatesserverside
> Also could you advise where to enable/disable the debug info below:
> Dec 29 15:13:45 Express-Demo.debug[91535] : Express.Server.AddSocket, socket: 12

All issues should be fixed with the demos.
The debug is socket id is removed.

Please make separated issues if for each if you can.
I will close this now since these are fixed.
